# Generated by Django 4.1.12 on 2023-10-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Action',
        ),
    ]
